export const giftSuggestions = [
  {
    title: "Personalized Wellness Retreat",
    description: "A curated self-care package with premium bath products, aromatherapy, and mindfulness tools.",
    priceRange: "75-150",
    tags: ["Wellness", "Self-care", "Relaxation"],
    forGender: ["female", "non-binary", "other"],
    minAge: 18,
    maxAge: 80,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Wellness+Retreat",
    baseMatchScore: 92,
  },
  {
    title: "Artisanal Cooking Experience",
    description: "A gourmet cooking kit with premium ingredients and expert video tutorials for a special meal.",
    priceRange: "80-200",
    tags: ["Cooking", "Gourmet", "Experience"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 16,
    maxAge: 90,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Cooking+Experience",
    baseMatchScore: 88,
  },
  {
    title: "Custom Adventure Map",
    description: "A personalized map highlighting shared memories and adventures, beautifully framed.",
    priceRange: "60-120",
    tags: ["Personalized", "Memories", "Art"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 20,
    maxAge: 80,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Custom+Map",
    baseMatchScore: 85,
  },
  {
    title: "Premium Tech Accessories Bundle",
    description: "Curated high-quality tech accessories that combine functionality with elegant design.",
    priceRange: "100-250",
    tags: ["Tech", "Practical", "Premium"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 16,
    maxAge: 70,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Tech+Accessories",
    baseMatchScore: 82,
  },
  {
    title: "Sustainable Fashion Subscription",
    description: "A subscription to ethically-made, sustainable fashion pieces selected for their style.",
    priceRange: "120-300",
    tags: ["Fashion", "Sustainable", "Subscription"],
    forGender: ["female", "non-binary", "other"],
    minAge: 18,
    maxAge: 65,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Sustainable+Fashion",
    baseMatchScore: 79,
  },
  {
    title: "Craft Spirits Tasting Experience",
    description: "A premium tasting kit with artisanal spirits and expert-guided virtual tasting session.",
    priceRange: "90-180",
    tags: ["Spirits", "Tasting", "Experience"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 21,
    maxAge: 90,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Spirits+Tasting",
    baseMatchScore: 76,
  },
  {
    title: "Bespoke Leather Accessories",
    description: "Customized leather goods with monogramming and premium craftsmanship.",
    priceRange: "80-200",
    tags: ["Leather", "Customized", "Luxury"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 20,
    maxAge: 80,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Leather+Accessories",
    baseMatchScore: 74,
  },
  {
    title: "Indoor Garden Ecosystem",
    description: "A self-sustaining indoor garden system with rare plants and smart monitoring.",
    priceRange: "100-250",
    tags: ["Plants", "Home", "Sustainable"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 18,
    maxAge: 90,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Indoor+Garden",
    baseMatchScore: 71,
  },
  {
    title: "Personalized Fitness Journey",
    description: "A custom fitness package with premium equipment and personalized training sessions.",
    priceRange: "150-300",
    tags: ["Fitness", "Wellness", "Personalized"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 16,
    maxAge: 75,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Fitness+Journey",
    baseMatchScore: 68,
  },
  {
    title: "Luxury Stationery Collection",
    description: "Handcrafted premium stationery with personalized elements and artisanal paper.",
    priceRange: "60-150",
    tags: ["Stationery", "Handcrafted", "Personalized"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 18,
    maxAge: 90,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Luxury+Stationery",
    baseMatchScore: 65,
  },
  {
    title: "Gourmet Chocolate Tasting Box",
    description: "A selection of premium chocolates from around the world with tasting notes and pairing suggestions.",
    priceRange: "40-100",
    tags: ["Food", "Gourmet", "Experience"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 16,
    maxAge: 90,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Chocolate+Tasting",
    baseMatchScore: 78,
  },
  {
    title: "Personalized Star Map",
    description: "A custom star map showing the night sky exactly as it appeared on a special date and location.",
    priceRange: "50-120",
    tags: ["Personalized", "Art", "Romantic"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 18,
    maxAge: 90,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Star+Map",
    baseMatchScore: 81,
  },
  {
    title: "Luxury Candle Collection",
    description: "Premium hand-poured candles with unique scent profiles and elegant vessels.",
    priceRange: "60-150",
    tags: ["Home", "Luxury", "Self-care"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 20,
    maxAge: 80,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Luxury+Candles",
    baseMatchScore: 77,
  },
  {
    title: "Personalized Book Subscription",
    description: "A curated monthly book delivery based on personal reading preferences and interests.",
    priceRange: "50-200",
    tags: ["Books", "Subscription", "Personalized"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 16,
    maxAge: 90,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Book+Subscription",
    baseMatchScore: 83,
  },
  {
    title: "Artisan Coffee Experience",
    description: "A premium coffee subscription with rare beans and brewing equipment from around the world.",
    priceRange: "70-180",
    tags: ["Coffee", "Gourmet", "Subscription"],
    forGender: ["female", "male", "non-binary", "other"],
    minAge: 20,
    maxAge: 80,
    imageUrl: "/placeholder.svg?height=300&width=400&text=Coffee+Experience",
    baseMatchScore: 75,
  },
]

